### ISSUE TITLE
instead of using videoFormatCombo to pass video quality args to youtube-dl you can use QlineEdit 

### ISSUE THREAD

**Issue by keshavbhatt** [trulex/YoutubeDL#1]
i cloned your repository and tweaked the interface and changed videoFormatCombo to a QlineEdit to pass the format codes . i implemented it and everything working fine . Inform me if you want my code .

**Comment by keshavbhatt** [comment]
doing that new feature added - download different format videos.

**Comment by trulex** [comment]
Of course, create a pull request.

**Comment by keshavbhatt** [comment]
i created a separate project but i would like to work in this too . https://github.com/keshavbhatt/ultimate-vedio-downloader.git

**Comment by keshavbhatt** [comment]
am new here on github so i will take some time to learn how it works so far i learned alot of things :100:

**Comment by keshavbhatt** [comment]
you need make another branch where i can pull my code i guess , teach me how can  i do that in case am wrong :/

**Comment by keshavbhatt** [comment]
or lets work on my repo i have added so many other features too like download path saving , different formats downloading , console logging etc and also fixed that update binary shit just check out the master branch in my project.
